### ISSUE TITLE
TG-2022-1Levantamentos Iniciais

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [Felipe-SNeves/YAD188-G02-iEduTCCProject#1]
# Objetivo
* Descrevam aqui:
    * Tema do trabalho (exemplo: App para adoção de PETs"
    * Breve descrição da situação problema (exemplo: Desenvolver um app para facilitar a adoção de Pets, tendo  como objetivo subjacente a criação de uma rede social com pessoas interessadas em cuidar de animais de estimação)
 
# Artefatos
Deverá ser postado **um arquivo**, formato PDF, cujo conteúdo deverá ter:
* Scrum Master 
    * Nome
    *  Responsabilidades
* Product Owner
    * Nome
    * Responsabilidades 
* Development Time
    Nome | papel | Responsabilidade 
    --------| ------ |--------------------
     xxx      |          |                               
     yyy      |          |                              
     zzz      |          |

**Comment by Felipe-SNeves** [comment]
# Artefato

Segue o artefato descrevendo o Scrum Team adotado para a disciplina.

[Scrum Team.pdf](https://github.com/Felipe-SNeves/YAD188-G02-iEduTCCProject/files/8216750/Scrum.Team.pdf)

**Comment by ProfVerissimoFatec** [comment]
Issue concluida com sucesso
Obrigado
