### ISSUE TITLE
Sprint#1 - Product Backlog & Sprint Backlog  (Data da Entrega: 16/03)

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [Felipe-SNeves/YAD188-G02-iEduTCCProject#3]
# Orientação para Entrega

O Grupo deve entregar nesta Issue ****somente**** Product Backlog & Sprint Backlog - no modelo enviado pela **_Profa. Ana Cláudia_** passou para vocês.

**Comment by Felipe-SNeves** [comment]
Segue o Product Backlog e a Sprint Backlog no modelo da professora. 
[Product Back Log _ Sprint.xlsx](https://github.com/Felipe-SNeves/YAD188-G02-iEduTCCProject/files/8258971/Product.Back.Log._.Sprint.xlsx)
