### ISSUE TITLE
Sprint#1 - Vídeo (gravação do Login + CRUD)  (Data da Entrega: 16/03)

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [Felipe-SNeves/YAD188-G02-iEduTCCProject#4]
# Orientação para Entrega

O Grupo deve entregar nesta Issue ****somente****  o vídeo produzido, e que será apresentado em aula

**Comment by Felipe-SNeves** [comment]
Vídeo para apresentação: https://www.youtube.com/watch?v=_GIIpq0imHo
*Obs: devido a duração do vídeo, ele será tocado em velocidade acelerada.
